- app.vue
- composables/useGrpcClient.ts
Signed-off-by: hi-rustin <rustin.liu@gmail.com>
> feat: add useGrpcClient

- components/TasksTable.vue
- composables/task.ts
- composables/tasks.ts
> feat: add style to fields

- app.config.ts
- app.vue
- composables/useGrpcClient.ts
- composables/useTasks.ts
https://github.com/hi-rustin/console-web/assets/29879298/674f48b9-6a6f-46ca-a03d-bef437404340
> feat: add error notification 

- app.vue
- components/TasksTable.vue
- composables/useTasks.ts
- pages/index.vue
- pages/tasks/[id].vue
- tests/components/__snapshots__/tasksTable.nuxt.spec.ts.snap
> feat: add task detail page

- components/HistogramChart.vue
- components/TaskDetails.vue
- tests/components/__snapshots__/taskDetails.nuxt.spec.ts.snap
https://github.com/hi-rustin/console-web/assets/29879298/e63f2bc3-5eae-4c09-86a9-203525e4814b
> fix: support responsive design

- components/TaskDetails.vue
- composables/tasks.ts
https://github.com/hi-rustin/console-web/assets/29879298/37a81fdf-845f-4e35-85fc-7a097ff8d328
> fix: only can access task details from homepage

- components/CHeader.vue
- components/TokioLogo.vue
- tests/components/__snapshots__/consoleHeader.nuxt.spec.ts.snap
> fix: do not add padding to logo and header

- components/TaskDetails.vue
- tests/components/__snapshots__/taskDetails.nuxt.spec.ts.snap
> feat: show fields

- components/TokioLogo.vue
- tests/components/__snapshots__/consoleHeader.nuxt.spec.ts.snap
> fix: add padding to logo

- components/TaskDetails.vue
- tests/components/__snapshots__/taskDetails.nuxt.spec.ts.snap
> feat: add state in the task divider

- components/TaskDetails.vue
- components/TaskTable.vue
- composables/task/duration.ts
- composables/task/tokioTask.ts
- composables/tasks.ts
- tests/components/__snapshots__/taskDetails.nuxt.spec.ts.snap
- tests/components/__snapshots__/taskTable.nuxt.spec.ts.snap
- tests/components/taskDetails.nuxt.spec.ts
- tests/components/taskTable.nuxt.spec.ts
> fix: use correct now timestamp

- app.vue
- components/ConsoleAnchor.vue
- tests/components/__snapshots__/consoleAnchor.nuxt.spec.ts.snap
- tests/components/consoleAnchor.nuxt.spec.ts
- utils/index.ts
https://github.com/hi-rustin/console-web/assets/29879298/3d098b04-b052-49ae-b699-14366ffc74dd
> feat: add console anchor

- components/ConsoleAnchor.vue
- tests/components/__snapshots__/consoleAnchor.nuxt.spec.ts.snap
> feat: highlight current route path

- components/ConsoleAnchor.vue
- components/ResourceDetails.vue
- components/TaskDetails.vue
- tests/components/__snapshots__/consoleAnchor.nuxt.spec.ts.snap
- tests/components/__snapshots__/resourceDetails.nuxt.spec.ts.snap
- tests/components/__snapshots__/taskDetails.nuxt.spec.ts.snap
> fix: align details page

- components/ResourceTable.vue
- composables/resources.ts
- composables/updateStream.ts
- types/resourceTableItem.ts
> fix: use correct parent ID

- components/ConsoleAnchor.vue
- tests/components/__snapshots__/consoleAnchor.nuxt.spec.ts.snap
- utils/index.ts
I don't think we need to drag it.
> feat: force anchor on the top

- .github/workflows/release.yml
- .github/workflows/test.yml
- app/public/subscriber.json
Signed-off-by: hi-rustin <rustin.liu@gmail.com>
> fix: use correct name for target address

- app/components/TaskTable.vue
- app/composables/tasks.ts
- app/composables/updateStream.ts
- app/package.json
- app/pnpm-lock.yaml
1. Added warning logs.
2. Added comments to the API.
> refactor: add logs and comments to tasks

- app/components/TaskDetails.vue
- app/types/task/tokioTask.ts
- app/types/taskBasicInfo.ts
See https://github.com/tokio-rs/console/blob/b158b05df583348c19029c17924b9c898a9e74ef/tokio-console/src/state/tasks.rs#L434
> fix: use the correct last wake duration

- app/components/TaskDetails.vue
- app/composables/tasks.ts
- app/types/timesDetails.ts
1. Stoped using undefined on TaskDetails interface.
2. Add logs and comments to useTaskDetails.
3. Simplified some code to make it more `javascript`.
> refactor: add comments and logs to useTaskDetails

- app/components/TaskDetails.vue
- app/composables/grpcClient.ts
- app/types/common/field.ts
- app/types/task/tokioTask.ts
- app/types/task/tokioTaskStats.ts
- app/types/taskBasicInfo.ts
- app/types/taskTableItem.ts
- app/types/timesDetails.ts
I just checked the TypeScript repo. They are all using undefined.
> refactor: use optional property instead of null

- app/app.config.ts
- app/composables/state.ts
- app/nuxt.config.ts
- app/package.json
- app/pnpm-lock.yaml
- app/tests/unit/field.test.ts
- app/types/taskBasicInfo.ts
- app/types/timesDetails.ts
We should always enable ts check during the building process.
> fix: enable ts check and make it compile

- app/tests/unit/duration.test.ts
- app/types/common/duration.ts
- app/types/common/durationWithStyle.ts
> fix: add precision for duration

- renovate.json
It is too annoying. Let's do it only once a month.
> chore: only bump deps once per month

- app/components/TaskDetails.vue
- app/composables/tasks.ts
- app/histogram/src/lib.rs
- app/nuxt.config.ts
- app/package.json
- app/pnpm-lock.yaml
- app/tests/components/taskDetails.nuxt.spec.ts
- app/types/task/tokioTaskDetails.ts
https://github.com/hi-rustin/tokio-console-web/assets/29879298/d938c997-5698-4002-859d-d4c77ec338bb
> feat: use dynamic size to build the histogram

- app/components/ResourceTable.vue
- app/composables/resources.ts
- app/tests/components/__snapshots__/resourceTable.nuxt.spec.ts.snap
- app/types/resourceTableItem.ts
> feat: add target column

- app/composables/resources.ts
- app/composables/tasks.ts
- app/types/common/field.ts
1. Added more comments to the funcs.
2. Added more logs when updating resources.
> refactor: add comments and logs

- app/components/ResourceTable.vue
- app/tests/components/__snapshots__/resourceTable.nuxt.spec.ts.snap
> fix: sort by resource id

- app/components/ResourceDetails.vue
- app/composables/resources.ts
- app/tests/components/__snapshots__/resourceDetails.nuxt.spec.ts.snap
- app/types/resourceBasicInfo.ts
> fix: remove useless pending state

- Cargo.lock
- Cargo.toml
> chore: bump the version to 0.1.1-beta.1

- app/composables/tasks.ts
https://github.com/hi-rustin/tokio-console-web/assets/29879298/c9389bdb-d570-41fd-b0fa-0aa486aa42a4
> fix: abort the task stream

- app/composables/grpcClient.ts
- app/composables/tasks.ts
- app/composables/updateStream.ts
Use `useMemoize` to cache the client.
> feat: cache the grpc client

- app/components/ResourceTable.vue
- app/components/TaskTable.vue
- app/tests/components/__snapshots__/resourceTable.nuxt.spec.ts.snap
- app/tests/components/__snapshots__/taskTable.nuxt.spec.ts.snap
> feat: only display one field or attribute

- app/components/AttributesPopover.vue
- app/components/FieldsPopover.vue
- app/components/LocationPopover.vue
- app/components/ResourceTable.vue
- app/components/TaskTable.vue
- app/tests/components/__snapshots__/resourceTable.nuxt.spec.ts.snap
- app/tests/components/__snapshots__/taskTable.nuxt.spec.ts.snap
> feat: Use popover to make the table small

- app/components/HistogramChart.vue
> refactor: use setup API for HistogramChart

- app/components/ConsoleMenu.vue
- app/components/PlayPauseButton.vue
- app/tests/components/__snapshots__/consoleMenu.nuxt.spec.ts.snap
Support pause and resume the stream.
https://github.com/hi-rustin/tokio-console-web/assets/29879298/52be903d-9ef6-45aa-b33a-04196e8a1b98
> feat: support pause the stream

- .github/renovate.json5
Follow up https://github.com/hi-rustin/tokio-console-web/pull/234
> chore: add renovate.json5 config file

- app/pnpm-lock.yaml
- app/tests/components/__snapshots__/consoleMenu.nuxt.spec.ts.snap
- app/tests/components/__snapshots__/resourceDetails.nuxt.spec.ts.snap
- app/tests/components/__snapshots__/resourceTable.nuxt.spec.ts.snap
- app/tests/components/__snapshots__/taskDetails.nuxt.spec.ts.snap
- app/tests/components/__snapshots__/taskTable.nuxt.spec.ts.snap
close https://github.com/hi-rustin/tokio-console-web/pull/244
> chore(deps): update dependency vue to v3.4.35

- app/composables/state.ts
- app/tests/components/__snapshots__/warningList.nuxt.spec.ts.snap
- app/tests/components/warningList.nuxt.spec.ts
- app/types/task/tokioTask.ts
- app/types/warning/taskWarnings/lostWaker.ts
- examples/grpc_web.rs
> feat: add LostWaker lint

- app/composables/state.ts
- app/tests/components/__snapshots__/warningList.nuxt.spec.ts.snap
- app/tests/components/warningList.nuxt.spec.ts
- app/types/task/tokioTask.ts
- app/types/warning/taskWarnings/selfWakePercent.ts
> feat: add SelfWakePercent lint

- app/components/WarningList.vue
- app/components/WarningsButton.vue
- app/composables/warnings.ts
- app/tests/components/warningsButton.nuxt.spec.ts
1. Added a chip for the warnings button.
2. Added a test for it.
> feat: add warnings chip

- app/app.vue
- app/components/SettingsCard.vue
- app/composables/state.ts
- app/composables/updateStream.ts
- app/stores/settings.ts
- app/tests/components/settingsCard.nuxt.spec.ts
> feat: make the retainFor configurable

- app/app.vue
- app/components/SettingsCard.vue
- app/composables/state.ts
- app/stores/settings.ts
- app/tests/components/settingsCard.nuxt.spec.ts
> feat: make linters configurable

- app/components/TaskDetails.vue
- app/tests/components/__snapshots__/taskDetails.nuxt.spec.ts.snap
- app/tests/components/__snapshots__/warningList.nuxt.spec.ts.snap
- app/tests/components/taskDetails.nuxt.spec.ts
- app/types/taskTableItem.ts
- app/types/warning/taskWarnings/selfWakePercent.ts
> feat: display warnings in task details page

- app/components/WarningList.vue
- app/components/WarningsButton.vue
- app/composables/warnings.ts
- app/tests/components/__snapshots__/warningList.nuxt.spec.ts.snap
- app/tests/components/warningsButton.nuxt.spec.ts
- app/types/warning/taskWarnings/neverYielded.ts
- app/types/warningItem.ts
> feat: show warning summaries correctly

- app/components/SettingsCard.vue
- app/tests/components/settingsCard.nuxt.spec.ts
> feat: add the default target URL

- .dockerignore
- .github/workflows/docker-build.yml
- Dockerfile
- package.json
- pnpm-lock.yaml
We need to regenerate the pnpm lock file; otherwise, an error will occur after the build in Docker.
> chore: Add a Dockerfile and fix the build process in Docker

- .github/workflows/docker-build.yml
- .github/workflows/publish.yml
- .github/workflows/relese-please.yml
1. Use release please to release and update markdown files.
2. Publish the docker image.
> ci: use release-please to release and publish docker image

- package.json
Follow up of https://github.com/Rustin170506/tokio-console-web/commit/0fd33b8d8f53c2be547ae55f6b34d0822d6b28ee
> chore: init the husky correctly

- README.md
> docs: recommend to use the docker image to run the app

- README.md
> docs: Refactor README to include an enable grpc_web section

- components/TaskTable.vue
- tests/components/taskTable.nuxt.spec.ts
Adds test to verify the Total column is sorted in descending order by default.
> fix: set the column sorting correctly

- components/ResourceTable.vue
- tests/components/__snapshots__/resourceTable.nuxt.spec.ts.snap
- tests/components/resourceTable.nuxt.spec.ts
- Added default sorting for the 'id' column in ResourceTable.
- Refactored tests to include a new test case for default sorting.
- Updated snapshots to reflect changes in ResourceTable rendering.
> fix: add default sorting to ResourceTable and update tests
